apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 9.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1
  config:
    server.publicBaseUrl: "https://localhost:5601"
    logging.root.level: debug
  http:
    tls:
      selfSignedCertificate:
        disabled: false
