filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: false
      templates:
        # Redis pod 0 - from StatefulSet
        - condition:
            and:
              - equals:
                  kubernetes.labels.app: "redis"
              - equals:
                  kubernetes.pod.name: "redis-0"
          config:
            - module: redis
              log:
                enabled: true
                var.hosts: ["${data.host}:6379"]
                var.password: "${kubernetes.default.redis-0-secret.password}"
              slowlog:
                enabled: true
                var.hosts: ["${data.host}:6379"]
                var.password: "${kubernetes.default.redis-0-secret.password}"
        # Redis pod 1 - from StatefulSet
        - condition:
            and:
              - equals:
                  kubernetes.labels.app: "redis"
              - equals:
                  kubernetes.pod.name: "redis-1"
          config:
            - module: redis
              log:
                enabled: true
                var.hosts: ["${data.host}:6379"]
                var.password: "${kubernetes.default.redis-1-secret.password}"
              slowlog:
                enabled: true
                var.hosts: ["${data.host}:6379"]
                var.password: "${kubernetes.default.redis-1-secret.password}"

# Enable kubernetes secrets provider to access secrets
providers.kubernetes_secrets:
  enabled: true

output.elasticsearch:
  hosts: ["https://${ELASTICSEARCH_HOST:elasticsearch-es-http.default.svc.cluster.local}:${ELASTICSEARCH_PORT:9200}"]
  username: "${ELASTICSEARCH_USERNAME:elastic}"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.verification_mode: "none"

setup.kibana:
  host: "https://${KIBANA_HOST:kibana-kb-http.default.svc.cluster.local}:${KIBANA_PORT:5601}"
  username: "${ELASTICSEARCH_USERNAME:elastic}"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.verification_mode: "none"
