---
# Note: This deployment references secrets from redis-secrets.yaml
# Make sure to apply redis-secrets.yaml before applying this file:
# kubectl apply -f redis-secrets.yaml
---
# Redis StatefulSet with 2 replicas
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        env:
        # Load both passwords as environment variables from secrets
        - name: REDIS_0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-0-secret
              key: password
        - name: REDIS_1_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-1-secret
              key: password
        command:
        - sh
        - -c
        - |
          # Extract pod ordinal from hostname (redis-0 -> 0, redis-1 -> 1)
          POD_ORDINAL=$(echo $HOSTNAME | sed 's/.*-//')

          # Dynamically get password from REDIS_{ordinal}_PASSWORD
          REDIS_PASSWORD=$(eval echo \$REDIS_${POD_ORDINAL}_PASSWORD)

          echo "Starting Redis pod-${POD_ORDINAL} with configured password"
          exec redis-server --requirepass "$REDIS_PASSWORD"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
---
# Individual Service for redis-0
apiVersion: v1
kind: Service
metadata:
  name: redis-0
  namespace: default
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-0
---
# Individual Service for redis-1
apiVersion: v1
kind: Service
metadata:
  name: redis-1
  namespace: default
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
    statefulset.kubernetes.io/pod-name: redis-1
