apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 9.4.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 1
  config:
    server.publicBaseUrl: "https://localhost:5601"
    logging.root.level: debug
    xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-es-http.elastic-system.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elastic-system.svc:8220"]
    xpack.fleet.packages:
      - name: fleet_server
        version: latest
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server Policy
        id: fleet-server-policy
        is_default_fleet_server: true
        package_policies:
          - name: fleet_server
            package:
              name: fleet_server
      - name: Agent Policy
        id: agent-policy
        is_default: true
        package_policies:
          - name: system
            package:
              name: system
  http:
    tls:
      selfSignedCertificate:
        disabled: false
